# Generated by Django 4.2.30 on 2026-04-19 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('course_type', models.CharField(choices=[('ort', 'Подготовка к ОРТ'), ('language', 'Языковые курсы'), ('other', 'Другое')], default='ort', max_length=20, verbose_name='Тип курса')),
                ('language', models.CharField(blank=True, choices=[('kg', 'Кыргызский'), ('en', 'Английский'), ('ru', 'Русский'), ('tr', 'Турецкий'), ('cn', 'Китайский'), ('de', 'Немецкий')], max_length=5, null=True, verbose_name='Язык')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('duration_months', models.PositiveIntegerField(default=3, verbose_name='Длительность (мес.)')),
                ('price_per_month', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена/месяц (сом)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('completed', 'Завершил'), ('dropped', 'Отчислен'), ('frozen', 'Заморожен')], default='active', max_length=20, verbose_name='Статус')),
                ('enrolled_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата зачисления')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='Дата завершения')),
                ('discount_percent', models.PositiveIntegerField(default=0, verbose_name='Скидка (%)')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Зачисление',
                'verbose_name_plural': 'Зачисления',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('parent_phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон родителя')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('school', models.CharField(blank=True, max_length=200, verbose_name='Школа')),
                ('grade', models.CharField(blank=True, max_length=10, verbose_name='Класс')),
                ('source', models.CharField(choices=[('instagram', 'Instagram'), ('referral', 'Рекомендация'), ('walk_in', 'Зашёл сам'), ('website', 'Сайт'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Источник')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('inactive', 'Неактивный'), ('graduate', 'Выпускник')], default='active', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата регистрации')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('bio', models.TextField(blank=True, verbose_name='Биография')),
                ('salary_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ставка (сом/час)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('hired_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата найма')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('courses', models.ManyToManyField(blank=True, to='core.course', verbose_name='Курсы')),
            ],
            options={
                'verbose_name': 'Учитель',
                'verbose_name_plural': 'Учителя',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('monthly', 'Ежемесячная оплата'), ('registration', 'Регистрационный взнос'), ('material', 'Учебные материалы'), ('other', 'Другое')], default='monthly', max_length=20, verbose_name='Тип оплаты')),
                ('method', models.CharField(choices=[('cash', 'Наличные'), ('transfer', 'Перевод'), ('card', 'Карта')], default='cash', max_length=20, verbose_name='Способ оплаты')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма (сом)')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('confirmed', 'Подтверждён'), ('cancelled', 'Отменён')], default='confirmed', max_length=20, verbose_name='Статус')),
                ('payment_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата оплаты')),
                ('period_month', models.DateField(blank=True, null=True, verbose_name='Оплачиваемый период')),
                ('receipt_number', models.CharField(blank=True, max_length=50, verbose_name='Номер квитанции')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='core.enrollment', verbose_name='Зачисление')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Записал')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('debt', 'Задолженность'), ('attendance', 'Посещаемость'), ('general', 'Общее')], max_length=20, verbose_name='Тип')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлено')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Время отправки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.student')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название группы')),
                ('schedule', models.CharField(choices=[('MWF', 'Пн/Ср/Пт'), ('TTS', 'Вт/Чт/Сб'), ('DAILY', 'Ежедневно'), ('SAT_SUN', 'Сб/Вс'), ('MON_FRI', 'Пн-Пт')], default='MWF', max_length=20, verbose_name='Расписание')),
                ('time_start', models.TimeField(blank=True, null=True, verbose_name='Время начала')),
                ('time_end', models.TimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('room', models.CharField(blank=True, max_length=50, verbose_name='Аудитория')),
                ('max_students', models.PositiveIntegerField(default=15, verbose_name='Макс. студентов')),
                ('status', models.CharField(choices=[('planned', 'Планируется'), ('active', 'Активная'), ('completed', 'Завершена')], default='planned', max_length=20, verbose_name='Статус')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='core.course', verbose_name='Курс')),
                ('students', models.ManyToManyField(through='core.Enrollment', to='core.student', verbose_name='Студенты')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='core.teacher', verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='enrollment',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.group', verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.student', verbose_name='Студент'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'group')},
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('status', models.CharField(choices=[('present', 'Присутствовал'), ('absent', 'Отсутствовал'), ('late', 'Опоздал'), ('excused', 'Уважительная причина')], default='present', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='core.enrollment', verbose_name='Зачисление')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Отметил')),
            ],
            options={
                'verbose_name': 'Посещаемость',
                'verbose_name_plural': 'Посещаемость',
                'ordering': ['-date'],
                'unique_together': {('enrollment', 'date')},
            },
        ),
    ]
