version: '3.9'

services:
  educrm:
    build:
      context: ./educrm_project
    container_name: educrm
    command: gunicorn educrm.wsgi:application --bind 0.0.0.0:7777
    volumes:
      - ./educrm_project:/app
      - educrm_volume:/app/staticfiles
    ports:
      - "7777:7777"
    restart: always

  restoran:
    build:
      context: ./restoran
    container_name: restoran
    command: gunicorn main.wsgi:application --bind 0.0.0.0:5555
    volumes:
      - ./restoran:/app
      - restoran_volume:/app/staticfiles
    ports:
      - "5555:5555"
    restart: always

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    network_mode: host
    command: tunnel --url http://localhost:5555
    restart: always

  toursite:
    build:
      context: ./toursite
    container_name: toursite
    command: gunicorn main.wsgi:application --bind 0.0.0.0:5000
    volumes:
      - ./toursite:/app
      - toursite_volume:/app/staticfiles
    ports:
      - "5000:5000"
    restart: always

volumes:
  educrm_volume:
  restoran_volume:
  toursite_volume:


    #  https://app-generator.dev/docs/products/django-libs/theme-soft-dashboard.html