version: '3.9'

services:
#  crm-system:
#    build:
#      context: ./crm-system
#    container_name: crm-system
#    command: gunicorn main.wsgi:application --bind 0.0.0.0:7000
#    volumes:
#      - .:/app
#      - crmsystem_volume:/app/staticfiles
#    ports:
#      - "7000:7000"
#    restart: always

  restoran:
    build:
      context: ./restoran
    container_name: restoran
    command: gunicorn main.wsgi:application --bind 0.0.0.0:6000
    volumes:
      - ./restoran:/app
      - restoran_volume:/app/staticfiles
    ports:
      - "6000:6000"
    restart: always

  toursite:
    build:
      context: ./toursite
    container_name: toursite
    command: gunicorn main.wsgi:application --bind 0.0.0.0:5000
    volumes:
      - ./toursite:/app
      - toursite_volume:/app/staticfiles
    ports:
      - "5000:5000"
    restart: always

volumes:
#  crmsystem_volume:
  restoran_volume:
  toursite_volume:


    #  https://app-generator.dev/docs/products/django-libs/theme-soft-dashboard.html